export const REQUEST_ISSUE_CREATION = "REQUEST_ISSUE_CREATION";
export const REQUEST_ISSUE_UPDATE = "REQUEST_ISSUE_UPDATE";
export const REQUEST_DATA = "REQUEST_DATA";
export const CREATE_ISSUE = "CREATE_ISSUE";
export const UPDATE_ISSUE = "UPDATE_ISSUE";
export const SET_STATE = "SET_STATE";
